
-- 1. Database Exploration

-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;


----------------------------------------------------------------------
-- 2. Dimensions Exploration

-- Explore all countries our customers are from
SELECT DISTINCT country
FROM gold.dim_customers;

-- Explore all product categories "The major divisions"
SELECT DISTINCT category
FROM gold.dim_products;


-- Explore all product categories and subcategories
SELECT DISTINCT category, subcategory
FROM gold.dim_products;


-- Explore all product categories, subcategories and products
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products;


-- Explore product lines
SELECT DISTINCT product_line
FROM gold.dim_products;


--------------------------------------------------------------------
-- 3. Date Exploration

-- Find the date of the first and last order
SELECT MIN(order_date) AS first_date,
       MAX(order_date) AS last_date
FROM gold.fact_sales;

-- How many years of sales are available
SELECT DATEDIFF(YEAR , MIN(order_date), MAX(order_date)) AS order_range_year
FROM gold.fact_sales;

-- Find the youngest and oldest customer
SELECT MIN(birth_date) AS oldest,
       DATEDIFF(YEAR, MIN(birth_date), GETDATE()) AS oldest_age,
       MAX(birth_date) AS youngest,
       DATEDIFF(YEAR, MAX(birth_date), GETDATE()) AS youngest_age
FROM gold.dim_customers;

---------------------------------------------------------------------------------------------
-- 4. Measures Exploration

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_items
FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_selling_price
FROM gold.fact_sales;

-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS total_num_orders
FROM gold.fact_sales;

-- Find the total number of products
SELECT COUNT(product_key) AS total_products
FROM gold.dim_products;

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers_placed
FROM gold.fact_sales;

-----------------------------------------------------------------------------------
-- 5. Magnitude Analysis

-- Find total customers by countries
SELECT country, COUNT(*) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY 2 DESC;

-- Find total customers by gender
SELECT gender, COUNT(*) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY 2 DESC;

-- Find total products by category
SELECT category, COUNT(*) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC;

-- What is the average costs in each category?
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC;

-- What is the total revenue generated for each category?
SELECT dp.category, SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY 2 DESC;

-- Find total revenue is generated by each customer
SELECT dc.customer_key,
       dc.first_name,
       dc.last_name,
       SUM(fs.sales_amount) AS total
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY total DESC;

-- What is the distribution of sold items across countries
SELECT dc.country,
       SUM(fs.quantity) AS total_distribution
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
on fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY 2 DESC;


--------------------------------------------------------------------------
-- 6. Ranking Analysis

-- Which 5 products generated the highest revenue?
SELECT TOP 5
       fs.product_key,
       p.product_name,
       SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON fs.product_key = p.product_key
GROUP BY fs.product_key, p.product_name
ORDER BY total_revenue DESC;


WITH products_ranking AS (
    SELECT p.product_name,
           SUM(fs.sales_amount) total_revenue,
           ROW_NUMBER() OVER (ORDER BY SUM(fs.sales_amount) DESC) AS rank_products
    FROM gold.fact_sales fs
    LEFT JOIN gold.dim_products p
    ON fs.product_key = p.product_key
    GROUP BY p.product_name
)
SELECT * FROM products_ranking
WHERE rank_products <= 5;


-- What are the 5 worst performing products in terms of revenue?
SELECT TOP 5
       fs.product_key,
       p.product_name,
       SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products p
ON fs.product_key = p.product_key
GROUP BY fs.product_key, p.product_name
ORDER BY total_revenue ASC;
















